name: New daily Pick

on:
  schedule:
    # Cron midnight
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Config Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute randomPick.py
        run: python src/scripts/randomPick.py

      - name: Git config
        run: 
          git config --global user.name "Dusty535"
          git config --global user.email "maximefelder535@gmail.com"

      - name: Commit
        run: |
          git add .
          git commit -m "new RandomPick"

      - name: Push
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}