name: Daily Update

on:
  schedule:
    # Cron midnight
    - cron: "55 21 * * *"

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Config Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/scripts/requirements.txt ]; then pip install -r src/scripts/requirements.txt; fi

      - name: execute py database update
        run: |
          python src/scripts/UpdataCharactersDatabase.py
          python src/scripts/UpdateCharactersAssets.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Daily Update Database"
          git push