name: New daily Pick

on:
  schedule:
    # Cron midnight
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Config Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute randomPick.py
        run: python src/scripts/randomPick.py

      - name: Push changes
        run: git config user.name "github-actions[bot]"
             git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
             git add .
             git commit -m "generated"
             git push