name: Exécuter le script randomPick tous les jours

# Définir la fréquence d'exécution de la pipeline
on:
  schedule:
    # Cette expression cron signifie "tous les jours à minuit"
    - cron: "0 0 * * *"

  # Permet d'exécuter manuellement le workflow via l'interface GitHub
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Exécuter le script randomPick.py
        run: python src/scripts/randomPick.py